### ISSUE TITLE
Bounty table Quest doesn't work, neither is the table itself.

### ISSUE THREAD

**Issue by Santereva** [ramity/vault-hunters-3#1]
In short, I had to use an admin command to complete the "craft the bounty table" quest and the table itself isn't generating any quests.

No clue as in why it isn't working, it just isn't.

![image](https://github.com/ramity/vault-hunters-3/assets/86306235/961d462f-4f67-4e0f-9554-99f9177c3bfd)

**Comment by Santereva** [comment]
Can't complete the "complete a bounty" quest either since I can't get bounties...

**Comment by ramity** [comment]
Thanks for your post. This issue isn't directly related to this repo, but I'm happy to help. It seems like the latest patch has some bugs to work out. Here's the quick fix:

```
/the_vault bounty reroll
```

The above _should_ give you your first 3 bounties. Let me know if this helps/resolves your issue.

**Comment by ramity** [comment]
Proactively closing this issue. I've verified that this is a known issue listed on the [discord](https://discord.gg/vaulthunters) > tech help channels # known-issues.
![image](https://github.com/ramity/vault-hunters-3/assets/8001375/f19232be-c6b6-4ec0-808e-6c8af32cd16b)

**Comment by Santereva** [comment]
Thank you for helping, the next time I get the chance I'll try it out!
